### ISSUE TITLE
Parcel-0 NFT tokenID starts at tokenId: 1 

### ISSUE THREAD

**Issue by Slyracoon23** [citydaoproject/parcel-contracts#12]
### **Description**

Parcel-0 NFT tokenID starts at tokenId: 1  instead of 0

### **Technical Details**

```
 uint256 nextToken = totalSupply() + 1;
    for (uint256 i; i < amount; i++) {
      _safeMint(account, nextToken + i);
    }
  }
```
Should be
```
 uint256 nextToken = totalSupply() ;
    for (uint256 i; i < amount; i++) {
      _safeMint(account, nextToken + i);
    }
  }
```
### **Acceptance Criteria**

-   Check first mint starts at 0

**Comment by mdnorman** [comment]
@Slyracoon23 why is this a problem? we definitely can't change it now, but I'm not sure what the issue is. it just means that 0 isn't used.

I specifically made this change in the code so that 0 wouldn't be minted since 0 is a problematic value for many functions, Several methods in contracts generally check for 0 values to mean "not set", and this can be problematic when "good" values equal 0, causing security issues.

**Comment by Slyracoon23** [comment]
@mdnorman it's not a problem. I think it's just keeping consistency. Your reply makes senses so I will close the issue.
